server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ltbo99?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ltbo99Aa

mybatis:
  type-aliases-package: com.hunau.domain
  mapper-locations: classpath:mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
